#!/bin/bash
# Claude Code Format Hook - Auto-generated by /setup-format-hook
# PostToolUse hook: runs formatter/linter after Edit/Write
#
# Exit code 規則：PostToolUse hook 永遠 exit 0
# - exit 2 會導致 UI 顯示 "blocking error"，誤導 agent 重試或卡住
# - Formatter/Linter 靜默執行，失敗也不阻擋（|| true 或 2>/dev/null）

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ] || [ ! -f "$FILE_PATH" ]; then
  exit 0
fi

EXT="${FILE_PATH##*.}"

case "$EXT" in
  js|jsx|ts|tsx|mjs|cjs)
    npx @biomejs/biome check --write "$FILE_PATH" 2>/dev/null || true
    ;;
  json|jsonc)
    npx @biomejs/biome check --write "$FILE_PATH" 2>/dev/null || true
    ;;
esac

exit 0
